//! Explicit NMOS opcode decoding. No unofficial aliases or CMOS extensions.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Op {
    Lda,
    Ldx,
    Ldy,
    Sta,
    Stx,
    Sty,
    Tax,
    Tay,
    Tsx,
    Txa,
    Txs,
    Tya,
    Inx,
    Iny,
    Dex,
    Dey,
    Inc,
    Dec,
    And,
    Ora,
    Eor,
    Bit,
    Cmp,
    Cpx,
    Cpy,
    Asl,
    Lsr,
    Rol,
    Ror,
    Bcc,
    Bcs,
    Beq,
    Bmi,
    Bne,
    Bpl,
    Bvc,
    Bvs,
    Jmp,
    Jsr,
    Rts,
    Pha,
    Php,
    Pla,
    Plp,
    Clc,
    Cld,
    Cli,
    Clv,
    Sec,
    Sed,
    Sei,
    Nop,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Mode {
    Imp,
    Acc,
    Imm,
    Zp,
    Zpx,
    Zpy,
    Abs,
    Abx,
    Aby,
    Ind,
    Izx,
    Izy,
    Rel,
}

/// Base cycles; only indexed reads and taken branches add cycles.
pub(crate) fn decode(opcode: u8) -> Option<(Op, Mode, u8)> {
    use Mode::*;
    use Op::*;
    Some(match opcode {
        0x01 => (Ora, Izx, 6),
        0x05 => (Ora, Zp, 3),
        0x06 => (Asl, Zp, 5),
        0x08 => (Php, Imp, 3),
        0x09 => (Ora, Imm, 2),
        0x0a => (Asl, Acc, 2),
        0x0d => (Ora, Abs, 4),
        0x0e => (Asl, Abs, 6),
        0x10 => (Bpl, Rel, 2),
        0x11 => (Ora, Izy, 5),
        0x15 => (Ora, Zpx, 4),
        0x16 => (Asl, Zpx, 6),
        0x18 => (Clc, Imp, 2),
        0x19 => (Ora, Aby, 4),
        0x1d => (Ora, Abx, 4),
        0x1e => (Asl, Abx, 7),
        0x20 => (Jsr, Abs, 6),
        0x21 => (And, Izx, 6),
        0x24 => (Bit, Zp, 3),
        0x25 => (And, Zp, 3),
        0x26 => (Rol, Zp, 5),
        0x28 => (Plp, Imp, 4),
        0x29 => (And, Imm, 2),
        0x2a => (Rol, Acc, 2),
        0x2c => (Bit, Abs, 4),
        0x2d => (And, Abs, 4),
        0x2e => (Rol, Abs, 6),
        0x30 => (Bmi, Rel, 2),
        0x31 => (And, Izy, 5),
        0x35 => (And, Zpx, 4),
        0x36 => (Rol, Zpx, 6),
        0x38 => (Sec, Imp, 2),
        0x39 => (And, Aby, 4),
        0x3d => (And, Abx, 4),
        0x3e => (Rol, Abx, 7),
        0x41 => (Eor, Izx, 6),
        0x45 => (Eor, Zp, 3),
        0x46 => (Lsr, Zp, 5),
        0x48 => (Pha, Imp, 3),
        0x49 => (Eor, Imm, 2),
        0x4a => (Lsr, Acc, 2),
        0x4c => (Jmp, Abs, 3),
        0x4d => (Eor, Abs, 4),
        0x4e => (Lsr, Abs, 6),
        0x50 => (Bvc, Rel, 2),
        0x51 => (Eor, Izy, 5),
        0x55 => (Eor, Zpx, 4),
        0x56 => (Lsr, Zpx, 6),
        0x58 => (Cli, Imp, 2),
        0x59 => (Eor, Aby, 4),
        0x5d => (Eor, Abx, 4),
        0x5e => (Lsr, Abx, 7),
        0x60 => (Rts, Imp, 6),
        0x66 => (Ror, Zp, 5),
        0x68 => (Pla, Imp, 4),
        0x6a => (Ror, Acc, 2),
        0x6c => (Jmp, Ind, 5),
        0x6e => (Ror, Abs, 6),
        0x70 => (Bvs, Rel, 2),
        0x76 => (Ror, Zpx, 6),
        0x78 => (Sei, Imp, 2),
        0x7e => (Ror, Abx, 7),
        0x81 => (Sta, Izx, 6),
        0x84 => (Sty, Zp, 3),
        0x85 => (Sta, Zp, 3),
        0x86 => (Stx, Zp, 3),
        0x88 => (Dey, Imp, 2),
        0x8a => (Txa, Imp, 2),
        0x8c => (Sty, Abs, 4),
        0x8d => (Sta, Abs, 4),
        0x8e => (Stx, Abs, 4),
        0x90 => (Bcc, Rel, 2),
        0x91 => (Sta, Izy, 6),
        0x94 => (Sty, Zpx, 4),
        0x95 => (Sta, Zpx, 4),
        0x96 => (Stx, Zpy, 4),
        0x98 => (Tya, Imp, 2),
        0x99 => (Sta, Aby, 5),
        0x9a => (Txs, Imp, 2),
        0x9d => (Sta, Abx, 5),
        0xa0 => (Ldy, Imm, 2),
        0xa1 => (Lda, Izx, 6),
        0xa2 => (Ldx, Imm, 2),
        0xa4 => (Ldy, Zp, 3),
        0xa5 => (Lda, Zp, 3),
        0xa6 => (Ldx, Zp, 3),
        0xa8 => (Tay, Imp, 2),
        0xa9 => (Lda, Imm, 2),
        0xaa => (Tax, Imp, 2),
        0xac => (Ldy, Abs, 4),
        0xad => (Lda, Abs, 4),
        0xae => (Ldx, Abs, 4),
        0xb0 => (Bcs, Rel, 2),
        0xb1 => (Lda, Izy, 5),
        0xb4 => (Ldy, Zpx, 4),
        0xb5 => (Lda, Zpx, 4),
        0xb6 => (Ldx, Zpy, 4),
        0xb8 => (Clv, Imp, 2),
        0xb9 => (Lda, Aby, 4),
        0xba => (Tsx, Imp, 2),
        0xbc => (Ldy, Abx, 4),
        0xbd => (Lda, Abx, 4),
        0xbe => (Ldx, Aby, 4),
        0xc0 => (Cpy, Imm, 2),
        0xc1 => (Cmp, Izx, 6),
        0xc4 => (Cpy, Zp, 3),
        0xc5 => (Cmp, Zp, 3),
        0xc6 => (Dec, Zp, 5),
        0xc8 => (Iny, Imp, 2),
        0xc9 => (Cmp, Imm, 2),
        0xca => (Dex, Imp, 2),
        0xcc => (Cpy, Abs, 4),
        0xcd => (Cmp, Abs, 4),
        0xce => (Dec, Abs, 6),
        0xd0 => (Bne, Rel, 2),
        0xd1 => (Cmp, Izy, 5),
        0xd5 => (Cmp, Zpx, 4),
        0xd6 => (Dec, Zpx, 6),
        0xd8 => (Cld, Imp, 2),
        0xd9 => (Cmp, Aby, 4),
        0xdd => (Cmp, Abx, 4),
        0xde => (Dec, Abx, 7),
        0xe0 => (Cpx, Imm, 2),
        0xe4 => (Cpx, Zp, 3),
        0xe6 => (Inc, Zp, 5),
        0xe8 => (Inx, Imp, 2),
        0xea => (Nop, Imp, 2),
        0xec => (Cpx, Abs, 4),
        0xee => (Inc, Abs, 6),
        0xf0 => (Beq, Rel, 2),
        0xf6 => (Inc, Zpx, 6),
        0xf8 => (Sed, Imp, 2),
        0xfe => (Inc, Abx, 7),
        _ => return None,
    })
}
