// Host-only preparation. Generated bytes and metadata come from the Rust host.
import { cpSync, mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const web = resolve(import.meta.dir, "..");
const root = resolve(web, "../..");
function run(args: string[], capture = false) {
  const result = Bun.spawnSync(args, {
    cwd: root,
    stdout: capture ? "pipe" : "inherit",
    stderr: "inherit",
  });
  if (result.exitCode !== 0)
    throw new Error(`${args.join(" ")} failed (${result.exitCode})`);
  return capture ? result.stdout.toString() : "";
}
run(["make", "wasm-build"]);
const assets = Bun.TOML.parse(
  run(
    ["cargo", "run", "--locked", "-p", "hesper", "--example", "web_assets"],
    true,
  ),
) as {
  demo: number[];
  demo_start: number;
  demo_done: number;
  presets: { id: string; blocks: { address: number; bytes: number[] }[] }[];
};
if (!assets.presets.length || !assets.demo.length)
  throw new Error("Empty host assets");
mkdirSync(resolve(web, "src/generated"), { recursive: true });
mkdirSync(resolve(web, "public/machine/programs"), { recursive: true });
const catalogue = {
  ...assets,
  presets: assets.presets.map((p) => ({
    ...p,
    blocks: p.blocks.map((block, index) => {
      const path = `machine/programs/${p.id}-${index}.bin`;
      writeFileSync(resolve(web, "public", path), Uint8Array.from(block.bytes));
      return { address: block.address, size: block.bytes.length, path };
    }),
  })),
};
writeFileSync(
  resolve(web, "src/generated/catalogue.json"),
  JSON.stringify(catalogue, null, 2) + "\n",
);
cpSync(
  resolve(root, "crates/cli/assets/wozmon.bin"),
  resolve(web, "public/machine/wozmon.bin"),
);
cpSync(
  resolve(root, "crates/cli/assets/README.md"),
  resolve(web, "public/machine/program-notes.md"),
);
cpSync(
  resolve(root, "crates/apple1/tests/data/README.md"),
  resolve(web, "public/machine/rom-notes.md"),
);
for (const name of ["apple1", "cpu6502"]) {
  cpSync(
    resolve(root, `target/wasm-packages/${name}/web`),
    resolve(web, `src/generated/${name}`),
    { recursive: true },
  );
  cpSync(
    resolve(root, `target/wasm-packages/${name}/web/README.md`),
    resolve(web, `public/machine/${name}-wasm-notes.md`),
  );
}
console.log(
  `Prepared ${catalogue.presets.length} presets, bundled Woz Monitor, CPU demo and both Wasm packages.`,
);
